[general]
import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[debug]
log_level = "Off"

[env]
TERM = "xterm-256color"

[font]
size = 15
normal.family = "JetBrainsMono NF"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[window]
decorations = "Buttonless"
dimensions.columns = 120
dimensions.lines = 35
padding.x = 15
padding.y = 15
