general.import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]
general.live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
SHELL = "/bin/zsh"
TERM = "xterm-256color"

[font]
size = 15

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
blur = false
decorations = "Buttonless"
dynamic_padding = true
startup_mode = "Windowed"

[window.dimensions]
columns = 120
lines = 35

[window.padding]
x = 15
y = 15
